import * as THREE from "three";
import { ICONS } from "@/assets/icons";

export const DASHBOARD_PREFIX = "dashboard";
export const WEBSITE_URL = "https://www.88residences.com";
const BASE_URL = import.meta.env.BASE_URL.endsWith("/")
  ? import.meta.env.BASE_URL.slice(0, -1)
  : import.meta.env.BASE_URL;

export const getAssetPath = (path) => `${BASE_URL}${path}`;

/**
 * Desktop navigation rail widths, in px.
 *
 * The rail itself is `position: absolute` (containers/sidebar-nav/index.jsx), so
 * it reserves no layout space of its own — layouts/main-layout must reserve a
 * matching width or the opaque white rail paints over the page content. Home
 * keeps the rail permanently expanded; inventory keeps it collapsed and expands
 * on hover, where the overhang lands on the 380px filter panel rather than on
 * the 3D canvas.
 */
export const SIDEBAR_WIDTH = {
  collapsed: 55,
  expanded: 225,
};

export const statusType = {
  SOLD: "sold",
  AVAILABLE: "available",
};

export const Preset = {
  ASSET_GENERATOR: "asset-generator",
};

export const UNIT_COLORS = {
  available: {
    base: "#4E8AEB",
    hover: "#1F5ED4",
    selected: "#1245AD",
  },
  sold: {
    base: "#E04F68",
    hover: "#C41832",
    selected: "#8B1022",
  },
};
export const OUTLINE_KEY = "__edgeLines";

export const STATUS_CONFIG = {
  available: { label: "available" },
  sold: { label: "sold" },
  reserved: { label: "reserved" },
};

export const ICON_PROPS_DEFAULT = { size: 20, strokeWidth: 1.8 };

export const UNIT_ICONS = {
  aptType: ICONS.AptType,
  bedrooms: ICONS.Bedrooms,
  area: ICONS.Area,
  balcony: ICONS.Balcony,
  type: ICONS.Type,
  price: ICONS.Price,
  direction: ICONS.Compass,
};

export const NAV_ITEMS = [
  { id: "home", label: "home", icon: ICONS.Home },
  { id: "inventory", label: "inventory", icon: ICONS.Package },
];

export const NAV_ITEMS_MOBILE = [
  { id: "home", label: "home", icon: ICONS.Home },
  { id: "inventory", label: "inventory", icon: ICONS.Package },
  { id: "more", label: "more", icon: ICONS.Menu },
];

export const FILTER_OPTIONS = {
  rooms: ["1", "2", "3", "studio"],
  direction: ["front", "rear", "side"],
  priceRange: { min: 140000, max: 350000 },
  areaRange: { min: 35, max: 105 },
};

// ── Ground ─────────────────────────────────────────────────────────────────────
export const GROUND_CONFIG = {
  size: 1200, // must exceed 2 * fadeDistance so the plane edge is never reachable
  floorColor: "#859d5b",
  cellColor: "#3f8f52",
  sectionColor: "#276b36",
  cellSize: 2,
  sectionSize: 10,
  cellThickness: 0,
  sectionThickness: 1.25,
  fadeDistance: 250,
  lodStart: 0.12,
  lodEnd: 0.35,
};

export const EXPOSURE = 0.0;
// export const EXPOSURE = 1;

export const CANVAS_GL_CONFIG = {
  antialias: false,
  toneMapping: THREE.ACESFilmicToneMapping,
  toneMappingExposure: Math.pow(2, EXPOSURE),
  powerPreference: "high-performance",
  outputColorSpace: THREE.SRGBColorSpace,
};

// ── Home masterplan scene ──────────────────────────────────────────────────────
// Generated by `npm run optimize:model` from the 117.61MB source: meshopt
// geometry compression, textures capped at 1024px, scene flattened/joined and
// GPU-instanced. 117.61MB -> 39.74MB, nodes 7,224 -> 318. All 11 glazing and 8
// railing material names survive the pipeline (--palette false is what protects
// them; palette generation would merge materials and rename them, breaking the
// name-based glazing lookup in use-home-scene.js). --simplify false keeps the
// architectural edges crisp.
export const HOME_MODEL_PATH = getAssetPath("/models/88RES-final-opt.glb");
export const HOME_ENV_PATH = getAssetPath("/hdr/80m-nano-green.jpg");

/**
 * Bounding box of all 436 meshes using a glass material. Windows exist only on
 * the seven buildings, so this IS the building envelope — measured by parsing
 * the GLB, not eyeballed. Size 55.21 x 18.60 x 182.82; the 3.3:1 plan ratio is
 * why framing has to be solved per aspect ratio.
 */
export const BUILDING_BBOX = {
  min: [-36.15, 1.8, -102.72],
  max: [19.06, 20.4, 80.1],
};

/**
 * Camera + orbit limits for the home masterplan scene.
 *
 * `target` is the measured centre of the seven buildings: the bounding box of
 * all 436 meshes using a glass material (windows only exist on the buildings)
 * spans X -36.15..19.06, Y 1.80..20.40, Z -102.72..80.10, so its midpoint is
 * [-8.5, 11.1, -11.3]. Orbiting about that point gives an equally well-framed
 * view from every azimuth.
 *
 * The camera is described by ANGLES, not a fixed position. The direction comes
 * from the gltfeditor reference render: the offset tuned on
 * features/big-scene-version-1 (camera [-173,53,-88] about target [-5,20,-7]) is
 * [-168, 33, -81] → azimuth -115.73°, elevation 10.03°.
 *
 * The DISTANCE is solved at runtime from the live canvas aspect by
 * features/home-scene/fit-camera.js, because no single value works everywhere:
 * a portrait phone needs ~484 units where a 1920x950 desktop needs ~192. The
 * reference render's own 189.4 clips the outer buildings on anything narrower
 * than about 2:1. Zoom limits are scales of that fitted distance so they mean
 * the same thing on every device.
 */
export const HOME_CAMERA = {
  target: [-8.5, 11.1, -11.3],
  azimuthDeg: -115.73,
  elevationDeg: 10.03,
  bbox: BUILDING_BBOX,

  baseFov: 35,
  baseAspect: 1.6,
  // 50° rather than 60°: portrait phones would otherwise need a fish-eye FOV to
  // hold the long axis. Past this point extra distance is the better lever.
  maxFov: 50,
  margin: 1.06,

  // The model's own PANO_Sphere dome has a radius of ~670 units, so the far
  // plane must clear maxDistanceCap + 670 = 1290. A 1:1600 near/far ratio also
  // keeps enough depth precision to avoid z-fighting on coplanar facades —
  // unlike the 0.5/4000 (1:8000) used on the prototype branch.
  near: 1,
  far: 1600,

  minDistanceScale: 0.6,
  maxDistanceScale: 1.6,
  // Hard ceiling: beyond this the camera would exit the PANO_Sphere dome and
  // the sky would vanish. Binds on portrait, where the fitted distance is 484.
  maxDistanceCap: 620,

  // The site is 3.3:1 in plan, so a steep top-down angle lands its 183-unit long
  // axis on the narrower vertical screen axis and clips. 35° keeps the aerial
  // high without becoming a map. 85° leaves 5° of headroom below the reference
  // framing — the reference elevation of 10.03° sits at polar 79.97°, so a hard
  // 80° limit would pin the camera to the boundary with nowhere to tilt down.
  minPolarDeg: 35,
  maxPolarDeg: 85,
};

/**
 * Renderer config for the home canvas.
 *
 * MSAA is safe here: unlike the inventory canvas there is no EffectComposer, so
 * there is no MSAA/SMAA buffer conflict. It is disabled on small screens because
 * a multisampled backbuffer is pure cost on a device already near its memory
 * ceiling with this model.
 */
/**
 * Exposure for the home canvas only, in stops. 0.4 -> toneMappingExposure 1.32.
 *
 * Separate from the shared EXPOSURE so the inventory canvas is unaffected.
 *
 * Why it is not 0: 80m-nano-green.jpg is an 8-bit sRGB JPEG, not an HDR, and its
 * zenith is deep navy. The measured cosine-weighted mean radiance for an
 * upward-facing surface is only 0.262 linear — sRGB 128 decodes to 0.216, so the
 * panorama carries far less light than its pixel values suggest. No combination of
 * light intensities alone can lift the scene without over-driving the sun and
 * crushing everything else into a 6:1 contrast ratio. Exposure is the correct
 * global lever, and NeutralToneMapping then rolls off the highlights.
 */
export const HOME_EXPOSURE = 0.4;

export const getHomeGlConfig = (isMobile) => ({
  antialias: !isMobile,
  // Neutral rolls off highlights rather than clipping them, which keeps bright
  // sky reflections from blowing out to flat white. It does compress the specular
  // peak, so reflection strength is bought back through material roughness and
  // envMapIntensity (see use-home-scene.js) rather than through tone mapping.
  toneMapping: THREE.NeutralToneMapping,
  toneMappingExposure: Math.pow(2, HOME_EXPOSURE),
  powerPreference: "high-performance",
  outputColorSpace: THREE.SRGBColorSpace,
});

/** Device-tiered device-pixel-ratio clamp for the home canvas. */
export const getHomeDpr = (isMobile) =>
  isMobile ? [1, 1.5] : [1, Math.min(window.devicePixelRatio, 2)];

const typeAConfig = {
  model: getAssetPath("/models/type-a-1024.glb"),
  hitbox: getAssetPath("/models/a-hitbox.glb"),
  heroAngle: 0,
  environment: {
    files: getAssetPath("/hdr/sky-40m-compressed.exr"),
    background: false,
    rotation: [0, 0, 0],
    backgroundRotation: [0, 0, 0],
    intensity: 1.0,
    resolution: 2048,
  },
  lighting: {
    // Match reference viewer: camera-attached lights at ~60° angle
    directIntensity: 0.03,
    directColor: "#ffffff",
    ambientIntensity: 1.35,
    ambientColor: "#ffffff",
    punctualLights: true,
    exposure: 0.0, // No tone mapping boost (Math.pow(2,0)=1.0)
    toneMapping: THREE.ACESFilmicToneMapping,
  },
};

export const BUILDING_CONFIG = [
  {
    name: "A",
    ...typeAConfig,
  },
  {
    name: "B",
    ...typeAConfig,
    hitbox: getAssetPath("/models/b-hitbox.glb"),
  },
  {
    name: "C",
    ...typeAConfig,
    hitbox: getAssetPath("/models/c-hitbox.glb"),
  },
  {
    name: "D",
    ...typeAConfig,
    model: getAssetPath("/models/type-d-final.glb"),
    hitbox: getAssetPath("/models/d-hitbox.glb"),
  },
  {
    name: "E",
    ...typeAConfig,
    model: getAssetPath("/models/type-f-1024.glb"),
    hitbox: getAssetPath("/models/e-hitbox.glb"),
  },
  {
    name: "F",
    ...typeAConfig,
    model: getAssetPath("/models/type-f-1024.glb"),
    hitbox: getAssetPath("/models/f-hitbox.glb"),
  },
  {
    name: "G",
    ...typeAConfig,
    model: getAssetPath("/models/type-g.glb"),
    hitbox: getAssetPath("/models/g-hitbox.glb"),
  },
];

export const DEFAULT_STALE_TIME = 1000 * 60 * 5;
