import { Color, MeshStandardMaterial } from "three";

export const unitData = [
  {
    name: "Box001",
    status: "available",
    type: "1BHK",
    area: "750 sq ft",
    price: "$250,000",
    floor: 1,
    direction: "North-East",
  },
  {
    name: "Box002",
    status: "sold",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },

  {
    name: "Box003",
    status: "available",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$350,000",
    floor: 1,
    direction: "North-West",
  },
  {
    name: "Box004",
    status: "sold",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },
  {
    name: "Box005",
    status: "available",
    type: "1BHK",
    area: "750 sq ft",
    price: "$255,000",
    floor: 2,
    direction: "North-East",
  },
  {
    name: "Box006",
    status: "sold",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },
  {
    name: "Box007",
    status: "available",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },
  {
    name: "Box008",
    status: "sold",
    type: "3BHK",
    area: "1750 sq ft",
    price: "$550,000",
    floor: 5,
    direction: "South-East",
  },
  {
    name: "Box009",
    status: "available",
    type: "1BHK",
    area: "750 sq ft",
    price: "$255,000",
    floor: 2,
    direction: "North-East",
  },
  {
    name: "Box010",
    status: "sold",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },
  {
    name: "Box011",
    status: "sold",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },
  {
    name: "Box012",
    status: "sold",
    type: "3BHK",
    area: "1750 sq ft",
    price: "$550,000",
    floor: 5,
    direction: "South-East",
  },
  {
    name: "Box013",
    status: "available",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },
  {
    name: "Box014",
    status: "sold",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },
  {
    name: "Box015",
    status: "available",
    type: "3BHK",
    area: "1750 sq ft",
    price: "$550,000",
    floor: 5,
    direction: "South-East",
  },
  {
    name: "Box016",
    status: "sold",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },
  {
    name: "Box017",
    status: "available",
    type: "3BHK",
    area: "1750 sq ft",
    price: "$550,000",
    floor: 5,
    direction: "South-East",
  },
  {
    name: "Box018",
    status: "sold",
    type: "2BHK",
    area: "1050 sq ft",
    price: "$355,000",
    floor: 2,
    direction: "North-West",
  },
  {
    name: "Box019",
    status: "available",
    type: "3BHK",
    area: "1750 sq ft",
    price: "$550,000",
    floor: 5,
    direction: "South-East",
  },
  {
    name: "Box020",
    status: "available",
    type: "3BHK",
    area: "1750 sq ft",
    price: "$550,000",
    floor: 5,
    direction: "South-East",
  },
];
export const statusType = {
  SOLD: "sold",
  AVAILABLE: "available",
};
export const getUnitMaterialConfig = ({ status }) => {
  const isSold = status === statusType.SOLD;

  const availableColor = new Color("#0080ff");
  const soldColor = new Color("#ff0000");

  return {
    baseColor: isSold ? soldColor : availableColor,
    hoverColor: isSold ? soldColor : availableColor,

    baseOpacity: isSold ? 0 : 0, // SOLD hidden initially
    hoverOpacity: 0.7, // both visible on hover

    emissive: isSold ? soldColor : availableColor,
  };
};
